# frozen_string_literal: true

require_relative "config/application"

Rails.application.load_tasks

require "rwm/rake"

cacheable_task :spec do
  sh "bundle exec rspec"
end

task :do_thing do
  puts "doing the thing in apps/worker"
end

task default: :spec
