# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development, :test do
  gem "rake"
  gem "rspec"
  gem "ruby_workspace_manager"
end

require "rwm/gemfile"
rwm_lib "auth"
