# frozen_string_literal: true

require "rwm/rake"

cacheable_task :spec do
  sh "bundle exec rspec"
end

task :bootstrap do
  puts "Add bootstrap steps for notifications here."
end

task :do_thing do
  puts "doing the thing in libs/notifications"
end

task default: :spec
