# frozen_string_literal: true

require "rwm/rake"

cacheable_task :spec do
  sh "bundle exec rspec"
end

task :bootstrap do
  puts "Add bootstrap steps for auth here."
end

task :do_thing do
  puts "doing the thing in libs/auth"
end

task default: :spec
